version: "3.6"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - my-network
    ports:
      - "3307:3306"
    volumes:
      -  mysql_db:/var/lib/mysql


  devops_app:
    depends_on:
      - mysql
    image: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:mysql://mysql:3306/devops_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql_db: