spring:
  application:
    name: devops-application

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/devops_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083

